### ISSUE TITLE
Why is monotonic_time being called every send/recv?

### ISSUE THREAD

**Issue by vans163** [mtrudel/thousand_island#1]
This seems like not only a very expensive locking operation, it could lead to clock skew on a heavily loaded server.

**Comment by mtrudel** [comment]
I actually just came against this a few days ago when profiling - it's used to drive duration metrics in telemetry, but actually ends up being quite expensive (about 10-15% of samples in relevant ExProf runs). I'm planning on looking into it properly in the next couple of weeks. 

telemetry support is still new (well really, the whole library is new :), so I'm happy to revisit how to accomplish this if you have any insight.

**Comment by mtrudel** [comment]
It would seem that `monotonic_time` is in fact the recommended 'cheapest' way to get the type of time we want, per https://erlang.org/doc/apps/erts/time_correction.html#Dos_and_Donts

It's also how Ecto does timing: https://github.com/elixir-ecto/db_connection/blob/07e8de85e5ddcf8e09945f17224f71b1da39f63e/lib/db_connection.ex#L1359

There isn't a way to lazily evaluate measurements in the telemetry package (which would reduce the exposure here to only cases where someone was listening to the given events.

Unsure about the best path forward here. Maybe remove timing information from send/recv telemetry events?

**Comment by vans163** [comment]
I see, did not realize Ecto used that too, maybe they use it for more precise / unique time?  

I am aware of :os.perf_counter/1 and :os.system_time/1,  both are very cheap but calling them multiple times produces the same values, they are not monotonic. :os.perf_counter works differently on windows and produces different values, :os.system_time/1 seems quite consistent across all platforms.  

Another option might be to spawn your own timer per process, and sample that.

**Comment by mtrudel** [comment]
I asked for advice on the matter in the #telemetry Slack channel; I'll report back if anything comes of it.

**Comment by mtrudel** [comment]
Advice from the telemetry channel was basically 'don't do that', so now we're not

**Comment by mtrudel** [comment]
Specifically though, monotonic_time does seem to be the correct source for these types of timings. The issue is more that neither it nor any other source of time is as cheap as I'd thought, so doing timings inside super hot functions is probably not the best approach.

**Comment by mtrudel** [comment]
Published as 0.1.3

**Comment by mtrudel** [comment]
Note from future self: it seems as if https://www.erlang.org/doc/man/os.html#perf_counter-0 and subsequent conversion via https://www.erlang.org/doc/man/erlang.html#convert_time_unit-3 may hold promise (note that the `perf_counter` time_unit type is not defined in Elixir's System module, so we need to appeal to Erlang directly).
