### ISSUE TITLE
handling non-TI messages within same GenServer fails after PR#96

### ISSUE THREAD

**Issue by dch** [mtrudel/thousand_island#104]
PR https://github.com/mtrudel/thousand_island/pull/96 adds guard rails to ensure message type matches thousand_island format.
However, it's possible to have additional messages, from outside thousand_island,
destined for the same genserver.

I use this functionality as a tcp proxy, sharing the same GenServer state. This
avoids message-passing overhead that would be introduced between the handler and
a further GenServer if they were separate processes.

- is this a reasonable intended use case for normal TI handlers, or
  should I go for the full custom implementation?

- the guard rails seem currently to prevent this, or am I holding it wrong?

I assume the macro expansions catch the additional handler messages before
my custom ones do, and I'm not clear if this can still be accommodated.

Example cribbed from [messenger.ex](https://github.com/mtrudel/thousand_island/blob/main/examples/messenger.ex) and [handler docs](https://github.com/mtrudel/thousand_island/blob/main/lib/thousand_island/handler.ex#L95-L110)

```elixir
#!/usr/bin/env elixir
Mix.install([{:thousand_island, github: "mtrudel/thousand_island"}])

defmodule Ecco do
  require Logger
  use ThousandIsland.Handler
  alias ThousandIsland.Socket

  @host "httpbin.org"
  @port 80
  @opts [:binary, active: true, nodelay: true]

  @impl ThousandIsland.Handler
  def handle_connection(%Socket{socket: client}, []) do
    {:ok, ip} = String.to_charlist(@host) |> :inet.getaddr(:inet)

    case :gen_tcp.connect(ip, @port, @opts) do
      {:ok, upstream} ->
        Logger.debug("connected to #{@host}:#{@port} via #{inspect(upstream)}")
        {:continue, %{upstream: upstream, client: client}}

      {:error, reason} ->
        Logger.debug("failed to connect to #{@host}:#{@port} because #{reason}")
        {:close, :upstream_connect_failed}
    end
  end

  @impl ThousandIsland.Handler
  def handle_data(data, _socket, state = %{upstream: upstream}) do
    # Send the data to the upstream service
    :gen_tcp.send(upstream, data)
    # Upstream response arrives asynchronously
    {:continue, state}
  end

  @impl GenServer
  def handle_info({:tcp, _port, _msg}, {socket, state}) do
    # just test the shape of the pattern matching in & out
    # ThousandIsland.Socket.send(socket, msg)
    # {:noreply, {socket, state}} also doesn't work
    {:noreply, {socket, state}, socket.read_timeout}
  end
end

# running the server
require Logger

{:ok, _pid} =
  ThousandIsland.start_link(
    port: 1234,
    handler_module: Ecco
  )

Logger.debug("listening on port 1234, curl me please")

unless IEx.started?() do
  Process.sleep(:infinity)
end
```

> you may need to remove ~/.cache/mix/installs/*/*/deps/thousand_island/
> to ensure you get latest main commit as dependency

Then running `curl --trace-ascii - http://localhost:1234` now fails:

```iex
16:22:59.843 [debug] listening on port 1234, curl me please

16:23:02.387 [debug] connected to httpbin.org:80 via #Port<0.9>

16:23:02.800 [error] GenServer #PID<0.499.0> terminating
** (RuntimeError)   The callback's `state` doesn't match the expected `{socket, state}` form.
  Please ensure that you are returning a `{socket, state}` tuple from any
  `GenServer.handle_*` callbacks you have implemented

    /home/dch/.cache/mix/installs/elixir-1.15.7-erts-13.2.2.4/3e8cc75637dec96c7c8ea27f725bf2fe/deps/thousand_island/lib/thousand_island/handler.ex:400: Ecco.handle_info/2
    (stdlib 4.3.1.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

Last message: {:tcp, #Port<0.9>, "HTTP/1.1 200 OK\r\n..."}

State: {%ThousandIsland.Socket{socket: #Port<0.7>,
  transport_module: ThousandIsland.Transports.TCP,
  read_timeout: 60000,
  silent_terminate_on_error: false,
  span: %ThousandIsland.Telemetry{...}},
  %{client: #Port<0.7>, upstream: #Port<0.9>}}
```

**Comment by mtrudel** [comment]
Hi Dave!

The issue is happening because you're receiving messages from another active socket. The [newly introduced pattern](https://github.com/mtrudel/thousand_island/blob/25af8b6d43dcf5294439758c458a2bb370eb90f8/lib/thousand_island/handler.ex#L399-L399) gets included into file at the point of the `use Handler` macro, so it'll match any `:tcp` or `:ssl` socket messages that aren't otherwise matched internally by Thousand Island a few lines up from the link above. 

Your use case is absolutely one we should support, so I'll have to figure out a better approach here. My first thought is a `@before_compile` hook to macro the warning clause in at the very end of the module definition, as `Phoenix.Endpoint` does. Got any better ideas?
