### ISSUE TITLE
GenServer #PID<0.656.0> terminating

### ISSUE THREAD

**Issue by moacirbishopcamata** [mtrudel/thousand_island#124]
Good morning, I'm getting an error stack:
I'm not able to locate exactly what causes this error, but I have the impression that it comes from "Bandit Server"
I'm using:

[error] GenServer #PID<0.656.0> terminating
** (stop) :econnaborted
Last message: {:tcp_error, #Port<0.29>, :econnaborted}
State: {%ThousandIsland.Socket{socket: #Port<0.29>, transport_module: ThousandIsland.Transports.TCP, read_timeout: 60000, silent_terminate_on_error: false, span: %ThousandIsland.Telemetry{span_name: :connection, telemetry_span_context: #Reference<0.2654146451.1321992198.4719>, start_time: -5764606668487680, start_metadata: %{remote_port: 60877, remote_address: {127, 0, 0, 1}, telemetry_span_context: #Reference<0.2654146451.1321992198.4719>, parent_telemetry_span_context: #Reference<0.2654146451.1321992194.5644>}}}, %{opts: %{http: [], websocket: [], http_1: [], http_2: []}, plug: {Phoenix.Endpoint.SyncCodeReloadPlug, {EVacinaPetWeb.Endpoint, []}}, handler_module: Bandit.HTTP1.Handler, http_1_enabled: true, http_2_enabled: true, requests_processed: 4}}

Windows 10 PRO with 16GB RAM, NVMe-2 500GB
Elixir v1.16.3
Erlang/OTP 26.2.5

**Comment by dch** [comment]
this is typically from a connection that has been terminated by the OS, possibly before elixir has had much of a chance to process it. Could be anything from firewalls, to incorrect TLS settings (only if you are running this with TLS ofc), or too many connections per process, according to OS.

There is slightly more info [here](https://www.erlang.org/docs/26/man/inet.html) but basically it means that Windows dropped or terminated the connection very very early, before Erlang VM got a chance to do anything with it.

**Comment by mtrudel** [comment]
What Dave said; early terminations seem like Dave's pet issue! 

If you're curious, there's some prior art for this https://github.com/mtrudel/thousand_island/pull/72 and https://github.com/mtrudel/thousand_island/pull/103, also courtesy of Dave. 

Closing for hygiene. If anything else comes up, feel free to open a new issue!
