### ISSUE TITLE
`ThousandIsland.Socket.getstat/1` returning `{:error, :einval}` on handle_close.

### ISSUE THREAD

**Issue by JVMartyns** [mtrudel/thousand_island#129]
I need to collect some telemetry metrics from the `[:thousand_island, :connection, :stop]` event, but the fields `[:send_oct, :send_cnt, :recv_oct, :recv_cnt]` were not coming through.

Upon investigating, I discovered that at the end of the connection, the private function `do_socket_close/2` is called, which executes `ThousandIsland.Socket.getstat/1`.

At this point, the error `{:error, :einval}` occurs, and the fields listed above are not included in the telemetry.

**Comment by mtrudel** [comment]
Thanks for the report!

Is it possible for you to provide a repro case?

**Comment by JVMartyns** [comment]
Define a Handler module just like in the documentation
```elixir
defmodule MyApp.Echo do
  use ThousandIsland.Handler

  @impl ThousandIsland.Handler
  def handle_data(data, socket, state) do
    ThousandIsland.Socket.send(socket, data)
    {:continue, state}
  end
end
```

Start the Handler in Application
```elixir
defmodule MyApp.Application do
  ...

  def start(_type, _args) do
    children = [
      ...
      {ThousandIsland, port: 1234, handler_module: MyApp.Echo}
    ]
  ...
  end
...
end
```

Add ConsoleReporter telemetry metrics to output to the console.
```elixir
defmodule MyAppWeb.Telemetry do
  ...

  @impl true
  def init(_arg) do
    children = [
      {:telemetry_poller, measurements: periodic_measurements(), period: 10_000},
      {Telemetry.Metrics.ConsoleReporter,
       metrics: [
         # Thousand Island Metrics
         summary("thousand_island.connection.stop.send_oct"),
         summary("thousand_island.connection.stop.send_cnt"),
         summary("thousand_island.connection.stop.recv_oct"),
         summary("thousand_island.connection.stop.recv_cnt")
       ]}
    ]

    Supervisor.init(children, strategy: :one_for_one)
  end

  ...
end

```

Use nc or another tool to establish a connection and then terminate it to trigger the "connection.stop" event.
```bash
~$ nc localhost 1234
echo
echo
^C
~$ 
```

```bash
[Telemetry.Metrics.ConsoleReporter] Got new event!
Event name: thousand_island.connection.stop
All measurements: %{monotonic_time: -576460734998206490, duration: 5176501932}
All metadata: %{error: :peer_closed, remote_port: 57232, remote_address: {127, 0, 0, 1}, telemetry_span_context: #Reference<0.781239206.4077649934.193101>, parent_telemetry_span_context: #Reference<0.781239206.4077649930.192855>}

Metric measurement: :send_oct (summary)
Measurement value missing (metric skipped)

Metric measurement: :send_cnt (summary)
Measurement value missing (metric skipped)

Metric measurement: :recv_oct (summary)
Measurement value missing (metric skipped)

Metric measurement: :recv_cnt (summary)
Measurement value missing (metric skipped)
```

**Comment by mtrudel** [comment]
Thanks for the repro! I don't think there's anything we can do here; by the time Thousand Island hears about the socket closure [here](https://github.com/mtrudel/thousand_island/blob/f25380dbb65610e8a2dd1155383d1e1fb9ee49b9/lib/thousand_island/handler.ex#L389-L389) it's already too late to be able to extract stats data from the underlying socket. We're at the mercy of the underlying implementation here, unfortunately.

**Comment by mtrudel** [comment]
Closing for hygiene - if there's any further improvement you think we can make here, please feel free to reopen!

**Comment by JVMartyns** [comment]
In this case, it would be better to update the documentation, since it is not possible to transmit these metrics.

**Comment by mtrudel** [comment]
Yep. Good call. I'll drop that in my notes for the next release.
