### ISSUE TITLE
changing the socket during transport.handshake

### ISSUE THREAD

**Issue by danielspofford** [mtrudel/thousand_island#141]
I have a custom transport whose `handshake/1` callback wishes to mutate the socket, but this does not seem possible right now according to https://github.com/mtrudel/thousand_island/blob/main/lib/thousand_island/socket.ex#L49 always returning the socket as it was prior to the handshake.

Is this an intentional constraint, or something that could be allowed in a future release?

Appreciate this library and your efforts. Hope I'm not missing something obvious or doing something silly.

**Comment by mtrudel** [comment]
Nice catch! I don't think there's any good reason for it to stay the way it is; likely an oversight on my part when I first wrote this.

Candidate fix is up at #142; are you able to validate that that does what you want?

**Comment by danielspofford** [comment]
Weeeee! I can try it right now...

**Comment by danielspofford** [comment]
Failing in a confusing way, will give more information when I understand what's going on.

**Comment by danielspofford** [comment]
@mtrudel confirmed all issues were on my end! Everything is working as expected 🎉.
