### ISSUE TITLE
Improve support for read timeouts

### ISSUE THREAD

**Issue by mtrudel** [mtrudel/thousand_island#15]
Currently, Thousand Island supports the notion of setting a timeout as part of the return value from `handle_connection` and `handle_data` calls. If this timeout is reached without more data being sent from the client, `handle_timeout` is called to allow the handler a mechanism to shut down the connection (or attempt to 'wake up' the client, etc). This mechanism is entirely tied to the async `handle_data` callback and doesn't have any effect on imperative `Socket.recv` calls (they have their own timeouts that map directly to the underlying `:gen_tcp` call).

Moreover, at the point of use this ends up with handler implementations having to carry around configured timeout values themselves, since the only place they can communicate them to Thousand Island is via callbacks. We can do better than this, especially considering that timeout values are usually a 'one-time' configuration point, and don't change throughout the lifetime of a connection.

It would be preferable to have a single harmonized way for handlers to specify timeouts. I'm thinking:

1. Add a `read_timeout` option to the list of `ThousandIsland.start_link` options (alongside eg. num_acceptors)
2. Plumb this value through to be stored in `ThousandIsland.Socket` structs
3. Extend the `ThousandIsland.Socket.recv` function to use this value in its call to the transport module's `recv` call if the caller doesn't pass in a more specific value (the current implementation just [defaults to `:infinity`](https://github.com/mtrudel/thousand_island/blob/main/lib/thousand_island/socket.ex#L80) in this case)
4. Do something similar with the timeout code in the handler's return value parsing at https://github.com/mtrudel/thousand_island/blob/main/lib/thousand_island/handler.ex#L378 (if an explicit timeout is returned by `handle_connection` or `handle_data` call then use it, otherwise fall back to the socket default).

If not specified, we should use a default value of `:infinity` to match current behaviour (and the semantics of the underlying socket). 

Once merged, the updated version of https://github.com/mtrudel/bandit/issues/8 can be addressed and a bunch of awkward bookkeeping code pulled out of Bandit's HTTP/2 handler.

**Comment by afsharalex** [comment]
I'll take a stab at it :)
