### ISSUE TITLE
Open telemetry?

### ISSUE THREAD

**Issue by mayel** [mtrudel/thousand_island#30]
I wonder if there's any plans to have an equivalent of https://github.com/open-telemetry/opentelemetry-erlang-contrib/tree/main/instrumentation/opentelemetry_cowboy ?

Related issues: https://github.com/open-telemetry/opentelemetry-erlang-contrib/issues/136 and https://github.com/mtrudel/bandit/issues/67

**Comment by mtrudel** [comment]
Absolutely there is! 

I hadn't seen that opentelemetry issue yet; thanks so much for bringing it to my attention! I'm midway through the process of redoing thousand island's telemetry implementation at #27, and am mostly blocked on it by figuring out the right way to associate span events. Given that a few spans start and end in different processes, and all of the parent / child span relations also span process boundaries, I've taken to adding explicit span IDs to telemetry events in the above PR. I've reached out to a couple of telemetry experts (most notably @bryannaegele) for advice on the suitability of this approach (with an end-goal of using it to power opentelemetry).

In the interest of issue hygiene I'll close this issue and suggest that we move any ongoing discussion onto #27. \

Thanks for the note!
