### ISSUE TITLE
Support for UDP transport

### ISSUE THREAD

**Issue by njouanin** [mtrudel/thousand_island#32]
Hi,
I'm interested in using thousand_island for writing a UDP server.
Is it a planned feature and/or would you mind some help writing this feature ?

**Comment by mtrudel** [comment]
UDP support is very much something that I'd like to land (and something I have a strict requirement for based on  https://github.com/mtrudel/bandit/issues/28), but I'm not sure yet that Thousand Island is the place for it. The UDP API is *very* different from TCP, and the `ThousandIsland.Transport` behaviour doesn't capture it well at all.

My *very* loose plan (that I haven't validated beyond very preliminary research) is Thousand Island will expose QUIC as a transport alongside TCP and TLS based on their similarities as connection-oriented protocols, and that Thousand Island's QUIC support would be based on UDP support implemented *somewhere* (I'm just not sure if that *somewhere* is within Thousand Island or its own project).

All that being said, I'm not planning on tackling this personally until after Bandit 0.8 lands. I would say that 90% of the difficulty in this workup would be building the right abstraction; the code-level work here is pretty close to trivial. What specific use cases were you looking at?

**Comment by njouanin** [comment]
I started working on an elixir implementation of the matter protocol which relies on UDP.
There's also a need for mDNS (UDP based) support.

**Comment by ryanwinchester** [comment]
> I started working on an elixir implementation of the matter protocol which relies on UDP.

Nice! I was working on Z-Wave for Elixir until SmartRent released Grizzly. Now, I'm not touching anything until I see how Matter pans out. 😅

**Comment by njouanin** [comment]
> Nice! I was working on Z-Wave for Elixir until SmartRent released Grizzly (which is great, btw). Now, I'm not touching anything until I see how Matter pans out. 😅

This is still early work. I still fight with specification documents which is not always clear ...

**Comment by mtrudel** [comment]
Closing due to nothing being actionable on Thousand Island's side.

**Comment by mtrudel** [comment]
I haven't started anything yet, but I've spent a bit of time researching and I'm not really sure yet what the right abstraction is here. UDP is rather a bit different and I'm conscious of not putting a round peg in a square hole. 

Do you have any implementation ideas? I'd love to chat them over!

**Comment by hissssst** [comment]
I thought about implementing `ThousandIsland.Transport` backed by `gen_udp`. Some callbacks like `handshake` or `secure?` could be simply ignored (or can return default values like `{:error, :not_implemented}` and `false`)

**Comment by hissssst** [comment]
Of course implementing `QUIC` is a different question. I am talking about vanilla UDP socket here

**Comment by hissssst** [comment]
Oh, I stumbled across some listener being incapable to handle UDP sockets, hmm
