### ISSUE TITLE
Acceptor pool race condition

### ISSUE THREAD

**Issue by danschultzer** [mtrudel/thousand_island#44]
With [TestServer](https://github.com/danschultzer/test_server) I often see these errors:

```elixir
03:40:44.098 [error] Task #PID<0.15608.0> started from #PID<0.15606.0> terminating
** (RuntimeError) Unexpected error in accept: :einval
    (thousand_island 0.5.17) lib/thousand_island/acceptor.ex:25: ThousandIsland.Acceptor.accept/3
    (elixir 1.14.2) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: &ThousandIsland.Acceptor.run/1
    Args: [{#PID<0.15360.0>, #PID<0.15606.0>, %ThousandIsland.ServerConfig{port: 58147, transport_module: ThousandIsland.Transports.TCP, transport_opts: [:inet], handler_module: Bandit.DelegatingHandler, handler_opts: %{handler_module: Bandit.InitialHandler, plug: {TestServer.Plug, {TestServer.HTTPServer.Bandit, [], #PID<0.15359.0>}}}, genserver_opts: [], num_acceptors: 100, read_timeout: 15000}}]
```

I suspect it has something to do with how I spin up/down bandit adhoc. A common use case would be start the server, quick test, then shut it down in the `on_exit` handler. `TestServer.start` calls `Bandit.start_link/1` and `TestServer.stop` calls `ThousandIslands.stop/1` in the above. 

I wonder if it's the `ThousandIsland.ShutdownListener` that breaks the supervision tree in some edge cases, since it seems that it can terminate the listener earlier than expected making it so the `Acceptor` is still starting up while the `Listener` process is killed:

```elixir
  def init(config) do
    children = [
      Supervisor.child_spec({ThousandIsland.Listener, config}, id: :listener),
      Supervisor.child_spec({ThousandIsland.AcceptorPoolSupervisor, {self(), config}},
        id: :acceptor_pool_supervisor
      ),
      {ThousandIsland.ShutdownListener, self()}
    ]

    Supervisor.init(children, strategy: :rest_for_one)
  end
```

Moving the shutdown listener up does resolve the issue, but that probably breaks the early draining logic? I haven't been able to isolate the problem and make a specific test for it. It happens with certain test seeds, so it might be reproducable. I'll try dig deeper to find out what exactly needs to happen for the `:einval` errors to be thrown, but maybe you already got a good idea what this could be @mtrudel? The port is not being reused btw.

**Comment by mtrudel** [comment]
I've seen these as well during test runs. Though it's benign, it's also noisy. 

I'm pretty sure your hunch is correct. Here's my hunch on the race:

1. The top-level `Server` process gets stopped. 
2. This terminates the `ShutdownListener` process, which shuts the `Listener` process down (reaching across the process tree to do so)
3. The `Listener` process shuts down, closing the underlying listener socket
4. Before the `Server` process has a chance to shut down all of its `Acceptor` children, an acceptor loops back to the `accept` call, passing in the (now closed) listener socket as an argument
5. We get an `:einval` error back, since that socket is no longer open for listening

Unsure offhand about the best way to mitigate this. Ideas?

**Comment by mtrudel** [comment]
FWIW this only started happening recently with me. I suspect it's likely due to a change in behaviour somewhere in OTP / underlying OS' handling of closed sockets. In any case, it needs fixin'

**Comment by mtrudel** [comment]
Fixed in 0.6.2, just released.

Thanks for the report @danschultzer !

**Comment by danschultzer** [comment]
Excellent thanks!

FWIW, I saw a bunch of these errors thrown inside the plug after updating:

```elixir
12:44:33.260 [error] Task #PID<0.19899.1> started from #PID<0.19897.1> terminating
** (stop) exited in: GenServer.call(#PID<0.19784.1>, :acceptor_info, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.14.2) lib/gen_server.ex:1038: GenServer.call/3
    (thousand_island 0.6.2) lib/thousand_island/acceptor.ex:10: ThousandIsland.Acceptor.run/1
    (elixir 1.14.2) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: &ThousandIsland.Acceptor.run/1
    Args: [{#PID<0.19783.1>, #PID<0.19897.1>, %ThousandIsland.ServerConfig{port: 51209, transport_module: ThousandIsland.Transports.TCP, transport_opts: [:inet], handler_module: Bandit.DelegatingHandler, handler_opts: %{handler_module: Bandit.InitialHandler, plug: {TestServer.Plug, {TestServer.HTTPServer.Bandit, [], #PID<0.19782.1>}}}, genserver_opts: [], num_acceptors: 100, read_timeout: 15000, parent_span_id: :undefined}}]
```

But it may just have been some weird build state, as I only saw it once. It all works correctly now! Just going to put it here for posteriority in case there's something that could trigger this.

**Comment by danschultzer** [comment]
BTW just to throw in my two cents on the mitigation itself:

I think your solution covers it. Not sure if there are other places where the dependency on listener process can cause issues. Ideally the supervision tree is terminated in the reverse order of how it was started to prevent this kind of race condition issues when some processes depends on other processes. If the acceptor depends on the listener pid, then ideally the acceptor should be terminated before the listener.
