### ISSUE TITLE
Cannot start multiple ThousandIsland children under a Supervisor

### ISSUE THREAD

**Issue by nickdichev** [mtrudel/thousand_island#48]
Hi, thanks for the awesome library. The ranch docs really leave me scratching my head after reading them so it's nice to have an Elixir interface with typespecs that I can actually understand. I thought it would be fun to port some Protohackers problems from ranch to ThousandIsland and I ran into a small issue when starting multiple `ThousandIsland` children in a supervision tree.

I defined a supervisor in my application as follows:

```elixir
defmodule Protohackers.Interface do
  use Supervisor

  alias Protohackers.Interface

  def start_link(opts) do
    Supervisor.start_link(__MODULE__, opts, name: __MODULE__)
  end

  def init(_opts) do
    children = [
      {ThousandIsland,
       handler_module: Interface.ThousandIsland.SmokeTest, port: 5555},
      {ThousandIsland,
       handler_module: Interface.ThousandIsland.PrimeTime, port: 5556},
      {Protohackers.RanchListener, protocol: Interface.Ranch.MeansToEnd, port: 5557}
    ]

    Supervisor.init(children, strategy: :one_for_one)
  end
end
```

I was getting the following error:

```
** (Mix) Could not start application protohackers: Protohackers.Application.start(:normal, []) returned an error: shutdown: failed to start child: Protohackers.Interface
    ** (EXIT) bad child specification, more than one child specification has the id: ThousandIsland.
If using maps as child specifications, make sure the :id keys are unique.
If using a module or {module, arg} as child, use Supervisor.child_spec/2 to change the :id, for example:

    children = [
      Supervisor.child_spec({MyWorker, arg}, id: :my_worker_1),
      Supervisor.child_spec({MyWorker, arg}, id: :my_worker_2)
    ]
```

What I noticed is that the top-level `ThousandIsland` supervisor hardcodes the Supervisor's `:id` to `__MODULE__` (https://github.com/mtrudel/thousand_island/blob/main/lib/thousand_island.ex#L144):

```elixir
  @doc false
  @spec child_spec(options()) :: Supervisor.child_spec()
  def child_spec(opts) do
    %{
      id: __MODULE__,
      start: {__MODULE__, :start_link, [opts]},
      type: :supervisor,
      restart: :permanent
    }
  end
```

So multiple children cannot be started under a supervision tree like they can be by calling `start_link` directly. I forked your project and solved this by essentially taking in the `:id` from `opts`. I'm happy to submit a PR, however, I have some questions:

1. Should this option bubble down past `child_spec`? I don't think it makes sense to pass it to `start_link` and try to shove it into the `ServerConfig` since this option really has nothing to do with the server, just the parent Supervisor.

2. What should be done about the typespec on `child_spec/1`? It shares the input type of `options()` with `start_link`, however, the `:id` is only really required for `child_spec/1`

Thanks!

**Comment by nickdichev** [comment]
Oh interesting, I haven't seen `child_spec/2` to override before. Thanks for pointing me to that. Just to test my understanding, I would have something like:

```elixir
    children = [
      Supervisor.child_spec({ThousandIsland, handler_module: Interface.ThousandIsland.SmokeTest, port: 5555}, id: :smoke)
      Supervisor.child_spec({ThousandIsland, handler_module: Interface.ThousandIsland.PrimeTime, port: 5556}, id: :prime)
    ]
```

Interesting suggestion. It certainly makes things easier from the application developer's point of view. Wouldn't a developer have to capture the returned ref and cache it somewhere in order to call `Supervisor.which_children/1`? This seems like it could make the startup of `ThousandIsland` messy to support a non-standard use case.

**Comment by mtrudel** [comment]
> Oh interesting, I haven't seen child_spec/2 to override before. Thanks for pointing me to that. Just to test my understanding, I would have something like:
>
>     children = [
>       Supervisor.child_spec({ThousandIsland, handler_module: Interface.ThousandIsland.SmokeTest, port: 5555}, id: :smoke),
>       Supervisor.child_spec({ThousandIsland, handler_module: Interface.ThousandIsland.PrimeTime, port: 5556}, id: :prime)
>     ]

Yep, exactly. It's the same pattern I [use](https://github.com/mtrudel/bandit/blob/main/lib/bandit/phoenix_adapter.ex#L62) in Bandit as well.

On second thought, I think I'll leave the id field unchanged here for now. If changes end up being made in the future I'll be sure to link back to this issue.

**Comment by mtrudel** [comment]
I'm going over Bandit & Thousand Island to try and square up the last breaking changes before a 1.0 in the near-ish future, and I think I'm going to change the `id` field after all.

Both Bandit and Thousand Island will be defining default ids in their child specs of the form `{__MODULE__, make_ref()}`. This will allow multiple instances inside a supervisor without trickery, and also easy identification of which child(ren) are of the respective type.

It'll be out as 0.6.7 later on today or tomorrow.

**Comment by mtrudel** [comment]
0.6.7 released with updates as above.
