### ISSUE TITLE
Thoughts on adopting PartitionSupervisor

### ISSUE THREAD

**Issue by Dowwie** [mtrudel/thousand_island#57]
Hey Mat,

Do you think that introducing PartitionSupervisor'd routing to DynamicSupervisors would be advantageous in thousand island?

**Comment by mtrudel** [comment]
Absolutely this is something useful! I'm going to keep this issue open to track discussion on it!

**Comment by ryanwinchester** [comment]
> I'm going to keep this issue open to track discussion on it!

(they already closed it, so you'll have to re-open it)

**Comment by mtrudel** [comment]
To be clear, are you proposing that Thousand Island provide facilities for managing listeners across a cluster, or to listen on one node but dispatch to handlers on disparate nodes? I don't believe the second of those is possible, and that (seems?) to be what you're asking about.

**Comment by Dowwie** [comment]
I was initially thinking about dynamic scaling of the pool.  I like where you went with the open-ended question, though. :)  This wasn't a well-formed idea and is why I closed the issue right away.

**Comment by mtrudel** [comment]
No actionable work here. Closing.
