### ISSUE TITLE
configurable acceptor pools

### ISSUE THREAD

**Issue by ruslandoga** [mtrudel/thousand_island#75]
Moved from https://github.com/mtrudel/bandit/issues/199

New plan:

- [ ] figure out https://github.com/mtrudel/thousand_island/issues/74 and redo the benchmarks (with a higher number of connections)
- [ ] more tcp-level benchmarks (e.g. accept rate)
- [ ] identify places in ThousandIsland where the acceptor pool can be configured, and what exactly acceptor pools need to implement for ThousandIsland+Bandit to work (e.g. suspend  / resume currently seem optional)
- [ ] check with the community if any of that configurability / alternative acceptor pools are actually desired

**Comment by ruslandoga** [comment]
How configuration could work:

### Ecto macro style

This approach allows for optional callbacks that are checked at compile-time.

```elixir
defmodule CustomPoolAdapter do
  @behaviour ThousandIsland.Pool
  @behaviour ThousnadIsland.Suspend

  # implementations
end

defmodule CustomPool do
  use ThousandIsland.Pool, adapter: CustomPoolAdapter
end

config :app, Bandit, pool: CustomPool
```

This idea worked better in my head when the configuration point was Bandit.

### Custom pool in as callback module

```elixir
defmodule CustomPool do
  @behaviour ThousandIsland.Pool
  
    def suspend(pid), do: raise "not implemented"
   # etc.
end

# similar to custom transports
config :app, ThousandIsland, pool_mod: CustomPool
```

**Comment by mtrudel** [comment]
Closing for hygiene. If you get this worked up @ruslandoga, feel free to open it as a PR!

Thanks again!
