### ISSUE TITLE
No way for handler to receive messages

### ISSUE THREAD

**Issue by lucacorti** [mtrudel/thousand_island#8]
Hi @mtrudel,

Thanks for working on this, it's pretty cool and has better ergonomics than ranch when developing in Elixir rather than erlang.

I'm running into something that should be easy to do, but currently is not possible with TI easily. I need to receive messages from processes other than Thousand Island over `handle_info` in my handler process.

Do you think it's possible to have TI handle only messages it is actually interested into and delegate the others to the handler?

**Comment by mtrudel** [comment]
If I understand your need correctly, that's absolutely something that TI does today (in fact, it was a primary design requirement when I was designing it). Look at the Messenger example at https://github.com/mtrudel/thousand_island/blob/main/examples/messenger.ex; I think that's what you need? It implements `handle_cast` within the handler process, but it's the same idea.

```

**Comment by mtrudel** [comment]
Note that the state you get passed in in non-TI handlers is in a tuple format (`{socket, state}`). A few other subtleties are discussed in the docs at https://hexdocs.pm/thousand_island/ThousandIsland.Handler.html#content

**Comment by lucacorti** [comment]
I see, but that's not exactly it. I have messages originated by some other process, not by the handler process itself, so I need to handle those via `handle_info` directly. Am I missing something?

**Comment by mtrudel** [comment]
The process behind a Handler is just a GenServer, so you're free to do any usual GenServer stuff in here including responding to `handle_call`, `handle_cast`, `handle_info`, etc. Assuming I understand your needs correctly, I think the following would be what you're looking for (this is basically just the Messenger example but changed to `handle_info` calls):

```elixir
defmodule Example do
  use ThousandIsland.Handler

  @impl ThousandIsland.Handler
  def handle_connection(socket, state) do
    IO.puts("#{inspect(self())} received connection")
    {:continue, state}
  end

  @impl ThousandIsland.Handler
  def handle_data(msg, _socket, state) do
    IO.puts("Received data from remote peer #{msg}")
    {:continue, state}
  end

  @impl GenServer
  def handle_info(msg, {socket, state}) do
    IO.puts("Received message in mailbox #{inspect(msg)}")
    {:noreply, {socket, state}}
  end
end
```

In other words, there's no 'magic' to Handler implementations - it's just a bit of macro sugar on top of normal GenServer calls (in fact, most of the actual implementation is pattern matching against `handle_info` calls coming from `:gen_tcp` / `:ssl`, as at https://github.com/mtrudel/thousand_island/blob/main/lib/thousand_island/handler.ex#L281-L300).

I hope I understand your problem correctly, but if not an example of what you're trying to accomplish would be super helpful.

**Comment by lucacorti** [comment]
Oh, sorry, I was looking at the handler code but missed that. I can just override `handle_info/2` in the handler. Sorry for the noise!

**Comment by mtrudel** [comment]
No problem!
