### ISSUE TITLE
Upgrading the transport mid-connection

### ISSUE THREAD

**Issue by icehaunter** [mtrudel/thousand_island#84]
We have a (partial) implementation of PostgreSQL server protocol that I recently ported to ThousandIsland. PostgreSQL protocol has a quirk: it always starts as plain TCP, then, as a first couple of bytes, client may send a request to update to one of the supported encrypted protocols - one of them being SSL. It's then expected of the server to run a SSL handshake and proceed over the socket under the SSL wrapping.

I understand that it is possible to achieve by hand-rolling a handler instead of `use ThousandIsland.Handler`, however it may be a useful feature to allow either returning something akin to a `:switch` tuple you have in Bandit, or just returning an updated socket - since all function on `ThousandIsland.Socket` just use `transport_module` field, it would be enough to allow smth like
```elixir 
def handle_data("magic message", socket, state) do
  socket = ThousandIsland.Transport.Ssl.handshake(socket, additional_ssl_options)
  socket = %{socket | transport_module: ThousandIsland.Transport.Ssl}
  {:continue, {socket, state}} # or {:switch, socket, state, _timeout} to be less conflicting
end
```

Because currently I don't see a way of upgrading the connection within `handle_connection`, and I think it would be a good feature.

I can probably offer up a PR if there is a consensus on the best return value for this

**Comment by mtrudel** [comment]
This should be doable (and pretty straightforward)!

Implementation wise, the change to Handler.handle_continuation should be modest;
  * We should use something like `{:switch, :ssl, ssl_options, state}` (and `{:switch, :ssl, ssl_options, state, timeout}`)
  * Call https://www.erlang.org/doc/man/ssl#handshake-2 (or /3 for the timeout stanza)
  * Upgrade the `transport_module` to reflect that we're now on SSL

**Comment by mtrudel** [comment]
I like this! I'm not sure that the contract for options generalizes but this is definitely a better first step!

**Comment by mtrudel** [comment]
I think if we change Transport.handshake to be arity 2 we can just have the convention that a switch calls that function on the new module

**Comment by icehaunter** [comment]
> I think if we change Transport.handshake to be arity 2 we can just have the convention that a switch calls that function on the new module

Yeah, exactly what I was planning to do

**Comment by mtrudel** [comment]
I like this approach a lot more. To be clear, I don't think any of the plumbing needs to be aware of SSL specifically; the 'switch' plumbing should be generic, and the SSL (or other future transport) specific bits should be hidden behind the new `handshake/2` callback
