### ISSUE TITLE
Inconsistent callback invoked when data received

### ISSUE THREAD

**Issue by haimiyahya** [mtrudel/thousand_island#87]
Please correct me if this is by design.

The nature of my complain is, I defined a supervisor like this:

```elixir
defmodule CPayFirewall.Supervisor do
  use Supervisor

  def start_link(args) do
    Supervisor.start_link(__MODULE__, args)
  end

  @impl true
  def init(args) do

    {:listening_port, listening_port} = List.keyfind(args, :listening_port, 0)
    {:connect_host, connect_host} = List.keyfind(args, :connect_host, 0)
    {:connect_port, connect_port} = List.keyfind(args, :connect_port, 0)
    {:timeout, _timeout} = List.keyfind(args, :timeout, 0)

    header_config = Application.fetch_env!(:cpay_tester, :template_of_ascii_message_header_and_bitmap_config)
    fields_formats = Application.fetch_env!(:cpay_tester, :iso_ascii_field_format)

    children = [
        {ThousandIsland, port: listening_port, handler_module: Mudahnyyyyya},
        {Registry, keys: :duplicate, name: :cpayfirewall_registry},
        {CPayFirewall.Client, host: connect_host, port: connect_port, timeout: 500000, opts: [active: true, mode: :binary], id: :cpayfirewall_client},
    ]

    # ThousandIsland.start_link(port: 1234, handler_module: Echo, handler_options: %{prev_message: <<>>})

    Supervisor.init(children, strategy: :one_for_one)
  end
end
```

Then I defined the handler module like this:

```elixir
defmodule Mudahnyyyyya do
  use ThousandIsland.Handler
  #import MessageAccumulator

  @impl ThousandIsland.Handler
  def handle_data(data, socket, state) do

    IO.inspect "what actually happened......"

    {:continue, state}
  end

  def terminate(socket, state) do
    {:continue, state}
  end

  @impl ThousandIsland.Handler
  def handle_connection(socket, state) do

    IO.inspect "client is connecting to x"

    disable_existing_connection("dummy")

    {:continue, state}
  end

  def handle_info({:forward_to_outside, msg}, {socket, state}) do

    IO.inspect "thousand island forwarding to ..."
    ThousandIsland.Socket.send(socket, msg)
    {:noreply, state}
  end

  def handle_info({:tcp, port, msg}, state) do

    IO.inspect "mudahnya"

    default_handle_info_tcp(msg, :tcp, nil, state)

    {:noreply, state}
  end

  def handle_info(a, {socket, state}) do
    {:noreply, state}
  end

  def default_handle_info_tcp(raw_message, _transport, _socket, state) do

    IO.inspect "forwarding to inside..."
    send(:firewall_internal, {:forward_to_inside, raw_message, self()})
    state

  end

  def disable_existing_connection(key) do

    registry_name = :cpayfirewall_registry

    case Registry.lookup(registry_name, key) do
      []  -> nil
      _   ->
        Registry.match(registry_name, "dummy", :enabled)
        |> Enum.each(fn {pid, _val} -> send(pid, :disable) end)

    end

    {:ok, _} = Registry.register(registry_name, key, :enabled)
  end

end
```

Also I defined a tcp client module:

```elixir
defmodule CPayFirewall.Client do

  use Connection
  import MessageAccumulator

  def child_spec(opts) do

    {:id, id} = List.keyfind(opts, :id, 0)

    %{
      id: id,
      start: {__MODULE__, :start_link, [opts]},
      type: :worker,
      restart: :permanent,
      shutdown: 500
    }
  end

  def start_link(args) do

    {:host, host} = List.keyfind(args, :host, 0)
    {:port, port} = List.keyfind(args, :port, 0)
    {:timeout, timeout} = List.keyfind(args, :timeout, 0)
    {:opts, opts} = List.keyfind(args, :opts, 0)

    Connection.start_link(__MODULE__, {host, port, opts, timeout}, name: :firewall_internal)
  end

  def init({host, port, opts, timeout}) do

    state = %{host: host, port: port, opts: opts, timeout: timeout, sock: nil, queue: [], prev_message: <<>>, txn_count: 0}

    {:connect, :init, state}
  end


  def connect(_condition, %{host: host, port: port, opts: opts, timeout: timeout} = state) do

    case :gen_tcp.connect(host, port, opts, timeout) do
      {:ok, sock} ->
        
        IO.inspect "connected to port " <> Integer.to_string(port)
        {:ok, %{state | sock: sock}}
      {:error, _} -> {:backoff, 1000, state}
    end
  end

  def handle_info({:tcp_closed, _socket}, state) do
    IO.inspect "socket closed"
    IO.inspect "attempt to reconnect"

    {:connect, :init, state}
  end


  def handle_info({:tcp, socket, msg_in}, %{prev_message: prev_message} = state) do

    {list_of_messages, extra_data} = get_message(prev_message <> msg_in, [])

    state = Enum.reduce(list_of_messages, state, fn msg, acc -> default_handle_info_tcp(msg, :gen_tcp, socket, acc) end)

    {:noreply, %{state | prev_message: extra_data}}
  end


  def handle_info({:forward_to_inside, raw_msg, _pid}, %{sock: sock, queue: queue, txn_count: txn_count} = state) do

    # introduce sleep in case server cannot keep up
    :timer.sleep(1)

    txn_count = txn_count + 1

    :gen_tcp.send(sock, raw_msg)

    IO.inspect "firewall request txn_count ^^^ : #{txn_count}"

    {:noreply, %{state | queue: queue, txn_count: txn_count}}
  end

  def default_handle_info_tcp(raw_message, _transport, _socket, %{queue: _queue} = state) do

    IO.inspect Registry.count(:cpayfirewall_registry)

    # find which connection is enabled then forward to that process
    Registry.match(:cpayfirewall_registry, "dummy", :enabled)
    |> Enum.each(fn {pid, _val} -> send(pid, {:forward_to_outside, raw_message}) end)

    state

  end


end
```

The purpose of the 3 modules is to act as intermediaries between a TCP server and a TCP Client like my drawing below:

{A very important application} <-- TCP -- {CPay firewall client} <-- erlang message -- {CPay firewall server (thousand island)} <-- TCP -- {some client}

What I found out is, in my current setup Thousand Island always call handle_info({:tcp, port, msg}, state) callback, however if I open command prompt do telnet to the port listened by the Thousand Island, callback handle_data(data, socket, state) will be called, I tried to write a separate TCP client that connect to the Thousand Island server also handle_data(data, socket, state) is called.

I hope my explanation is clear.

**Comment by haimiyahya** [comment]
Thank you for the response.

The purpose I added handle_info({:tcp, port, msg}, state) callback is due to this error if it was not exists.

06:12:26.119 [error] GenServer #PID<0.902.0> terminating
** (FunctionClauseError) no function clause matching in Mudahnyyyyya.handle_info/2
    (cpay_tester 0.1.0) deps/thousand_island/lib/thousand_island/handler.ex:2: Mudahnyyyyya.handle_info({:tcp, #Port<0.24>, <<1, 48, 73, 83, 79, 48, 50, 53, 48, 48, 48, 48, 55, 55, 48, 50, 49, 48, 66, 50, 51, 65, 67, 54, 48, 49, 50, 69, 67, 48, 56, 50, 49, 56, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, ...>>}, [])
    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:tcp, #Port<0.24>, <<1, 48, 73, 83, 79, 48, 50, 53, 48, 48, 48, 48, 55, 55, 48, 50, 49, 48, 66, 50, 51, 65, 67, 54, 48, 49, 50, 69, 67, 48, 56, 50, 49, 56, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, ...>>}
State: []

**Comment by mtrudel** [comment]
I think I see the issue; it's not the `{:tcp, _, _}` clause that you're having a hard time matching, it's the `{socket, state}` tuple. If you look at your other `handle_info` callbacks, they only return the `state` as matched in the second tuple element. Per point [number 4 at the top of the Handler documentation](https://hexdocs.pm/thousand_island/ThousandIsland.Handler.html#callbacks), you need to return the entire `{socket, state}` tuple (i.e.: your return value should be `{:noreply, {socket, state}}`, not `{:noreply, state}`. I suspect those callbacks are being called first, which are then destroying the internal structure of the handler by not returning the entire tuple.

I wish that API were more ergonomic, but there's no other way to intercept the built-in behaviour of GenServer without having to rely on this behaviour; I wanted Thousand Island to add as little 'magic' as possible on top of GenServer, which has the side effect that sometimes awkward things like this seep through.

**Comment by haimiyahya** [comment]
I changed my existing handle_info callbacks to return {:noreply, {socket, state}} now it works (def handle_data(data, socket, state) now being called).

Thank you very much.

```elixir
def handle_info({:forward_to_outside, msg}, {socket, state}) do

    #transport.send(socket, msg)
    IO.inspect "thousand island forwarding to paynet"
    ThousandIsland.Socket.send(socket, msg)
    {:noreply, {socket, state}}
  end
```

I wonder if it is really not possible to design so the handle_info just need to return similar value like a normal genserver? Probably by using monad or macros?

**Comment by mtrudel** [comment]
> I wonder if it is really not possible to design so the handle_info just need to return similar value like a normal genserver?

That's the thing; I was (and remain) steadfast in keeping Thousand Island as thin of a layer as possible over top of the underlying layers (GenServer, :gen_tcp, and :ssl). The transparency of being able to say 'when you `use ThousandIsland.Handler`, all you're doing is including in a bunch of standard GenServer calls' is very compelling. It's a good example of 'less is more', and adding in a bunch of complexity (as you correctly point out I could do with macros or more clever state types) is counter to this approach. I agree that this particular case requires more awareness than is ideal, but it also helps highlight the underlying simplicity of the model, which reinforces the library's ultimate prime directive, namely ['to be easy to understand & reason about'](https://hexdocs.pm/thousand_island/ThousandIsland.html).
