### ISSUE TITLE
A way to align custom and library `GenServer` responses

### ISSUE THREAD

**Issue by elfenlaid** [mtrudel/thousand_island#94]
Hello there 👋

Thank you for such a great library!

There's a tiny itch that I've encountered while while implementing a `ThousandIsland.Handler`. I want to discuss whether it makes sense to solve it the way I did it and whether it makes sense to solve it on the library level.

So, I created a couple of `GenServer.handle_info/cast/call` callbacks while implementing a `ThousandIsland.Handler`. Everything works superb. What's more, those handlers share the logic with `ThousandIsland.Handler.handle_data` aside from one thing -  return values.

I end up with the function that casts `ThousandIsland.Handler.handler_result()` to what `GenServer` handlers expect. Such function exists in the library - `ThousandIsland.Handler.handle_continuation/2`, but it's private.

I wonder whether it would make sense to make the function public? This way, library clients can tap into `GenServer` logic, but align their responses to what `ThousandIsland.Handler` does under the hood with its callbacks. E.g., share the same shutdown methods, or use `socket.read_timeout` as a default value for `GenServer` responses, and such.

Edit: a tiny PR that demonstrates the proposition https://github.com/mtrudel/thousand_island/pull/95

**Comment by mtrudel** [comment]
First up, I'd *love* to be able to bridge this gap! Thanks for chiming in!

To try and explain my understanding back to you, this is how people have to implement `handle_info` calls within a handler today:

```elixir
...
  def handle_info(msg, {socket, state}) do
    # Do a thing with `msg` in the context of `state`, possibly making use of `socket`
    {:noreply, {socket, state}
  end
```
If I understand your proposal, the idea would be to allow people to write like this:

```elixir
  def handle_info(msg, {socket, state}) do
    # Do a thing with `msg` in the context of `state`, possibly making use of `socket`
    {:continue, state}
    |> ThousandIsland.Handler.handle_continuation(socket)
  end
```

Do I have this right?

**Comment by elfenlaid** [comment]
Yeap, that's exactly it. My concern, though, is that it might be too specific a case. But I've come across it three times now. 

In other words, maybe there are more ways to iron it out, but it seems that making a function public in the most straightforward one that I came up with 😅

**Comment by mtrudel** [comment]
Got it. Thanks for clarifying. 

I think this may be *part* of an overall solution, but on its own it makes things more confusing since it requires the user to **match** on the standard GenServer pattern, (albeit with the private `{socket, state}` argument), but **return** the ThousandIsland `{:continue, state}` style pattern. 

An ideal solution would let us use one or the other style for both the function signature pattern and also its return value. 

Here's a couple of ideas I've had bouncing around my head for a while. They both have shortcomings, but maybe we can cook something better up together:

1. We add this inside ThousandIsland.Handler's `__using__` macro:

```elixir
  def handle_info(msg, {socket, state}) do
    handle_info(msg, state)
    |> case do
      {:noreply, state} -> {:noreply, {socket, state}}
      # (clauses for all the other valid returns from c:GenServer.handle_info/2)
      other -> handle_continuation(other, socket)
    end
  end

  # (Similar for handle_call, handle_cast, etc)  
```

This would let handle_* implementations that didn't want to know or care about the socket to work *exactly* as they would outside of Thousand Island. If you wanted to interact with the socket, you'd be on the hook to do so using the existing `{socket, state}` tuple convention on call & return.

----

2. We add this inside ThousandIsland.Handler's `__using__` macro, after the existing internal handle_info functions:

```elixir
      def handle_info({msg, raw_socket, data}, state) when msg in [:tcp, :ssl] do
        raise "You didn't return a {socket, state} tuple on a previous handle_* call you fool!"
      end
```

This would make it obvious to people that did the wrong thing in their handle_* calls, though only after the fact when the socket next tries to receive data. For completeness, we'd want to add such fall through handlers to all the possible internal callbacks, including `terminate`

I like this one better, I think.

WDYT?

**Comment by elfenlaid** [comment]
> I think this may be _part_ of an overall solution, but on its own it makes things more confusing since it requires the user to **match** on the standard GenServer pattern, (albeit with the private `{socket, state}` argument), but **return** the ThousandIsland `{:continue, state}` style pattern.

Fully agree, the result API feels awkward to use!

> We add this inside ThousandIsland.Handler's __using__ macro, after the existing internal handle_info functions:

I also like this idea better.

---

Ruminating more on your first suggestion, we might boost it a bit:

- Define optional callbacks for `handle_cast/3, handle_info/3, handle_call/3`
- Check whether the module defines any of these
- Add intermediate `handle_cast/2, handle_info/2, handle_call/2` that would bridge the gap:

```elixir
def handle_info(msg, {socket, state}) do
    msg
    |> handle_info(socket, state)
    |> handle_continuation(socket)
end
```

I'm not sure whether it's okay to name these functions `handle_cast/3, handle_info/3, handle_call/3` or it's better to add some prefix like `handle_socket_call`. Otherwise it might break clients API in weird ways 😅 

Also, I'm not sure how this would interact with already defined "catch them all" handlers. Ideally we would want to put these bridging handle_* at the very end of the module to give existing handle_* a chance to pattern match.

Do you think any of this makes sense?

**Comment by elfenlaid** [comment]
> Yeah, I've thought about that approach too. I'm not nuts about it, mostly because I want to keep things as simple and transparent as possible & avoid abstractions as much as I can.
> 
> The more I think about it, the more I think that the answer here is to not do _anything_, other than make it REALLY APPARENT in docs that folks need to follow the existing pattern. This keeps the amount of magic to a minimum, and also helps keep it clear (once people understand things, at least) how we're just a thin layer on top of the GenServer they already know and love.

Aha, this makes sense. Huge props for providing the context behind the decision making.
This discussion has been quite fruitful already, I might steal some tips for my codebase 🙇 

> That being said, I think the idea of catching and erroring on cases where we get a `{:tcp,...` message with a malformed state might be useful, as I'd mused about above. Keeps things simple and transparent, and also gives people a gentle nudge towards more understanding at exactly the time they'd start scratching their heads.

This won't hurt, let me try it out and see what you would think.

**Comment by mtrudel** [comment]
I love it! Let's move the discussion over to that PR!
